<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Software Purchase</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="field" name="ORDER_NUM" /></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 0 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" /></b><br /><br />
			
			Thank you for your recent order. Here is the information you need to download and register your new software.
			
				<table border="0" cellpadding="0" cellspacing="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;">
					<tr>
						<td style="padding:15px 0 5px 0;"><b>License Key:</b> <custom type="field" name="SOFTWARE_KEY" /></td>
					</tr>
					<custom type="field" name="DOWNLOAD_LINK" optional="yes">
						<tr>
							<td style="padding:0 0 5px 0;"><b>Download Link:</b> <custom type="anchor" style="color:#222222; text-decoration:underline;" href="[DOWNLOAD_LINK]"><custom type="field" name="DOWNLOAD_LINK" /></custom></td>
						</tr>
						<tr>
							<td style="padding:15px 0 5px 0;">Should you have any technical problems, please contact <custom type="field" name="ELD_CONTACT_NAME" /> at <custom type="field" name="ELD_CONTACT_INFO" />.</td>
						</tr>
					</custom>
					<custom type="field" name="DOWNLOAD_LINK" optional="yes" mustEqual="">
						<tr>
							<td style="padding:10px 0 0 0;">For download and authorizing instructions, please choose the appropriate software brand below.
								<table border="0" cellspacing="0" cellpadding="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;">
								<tr>
									<td colspan="2" height="16" style="padding:0 0 0 0; font-size:16px; line-height:1px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Presonus</b> <span style="font-size:10px;">(authorizing will activate full version)</span><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.presonus.com/products/studio-one/download">http://www.presonus.com/products/studio-one/download</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Rob Papen</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.robpapen.com/yourdetails/index.php?action=account">http://www.robpapen.com/yourdetails/index.php?action=account</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Samplelogic</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.samplelogic.com/vssd.html">http://www.samplelogic.com/vssd.html</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Softube</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://softube.se/download/">http://softube.se/download/</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Sonnox</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.sonnox.com/register">http://www.sonnox.com/register</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Studio Devil</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.studiodevil.com/download/index.php">http://www.studiodevil.com/download/index.php</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Toontrack</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.toontrack.com/faq/">http://www.toontrack.com/faq/</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>TuneCore</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.tunecore.com/redeem">http://www.tunecore.com/redeem</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Vienna Instruments</b><br />
									<a style="color:#222222; text-decoration:underline;" href="https://www.vsl.co.at/en/68/141/591.vsl">https://www.vsl.co.at/en/68/141/591.vsl</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Waves Software</b><br />
									<a style="color:#222222; text-decoration:underline;" href="https://www.waves.com/login">https://www.waves.com/login</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Xils</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.xils-lab.com/pages/Redeem-Resale-Code.html">http://www.xils-lab.com/pages/Redeem-Resale-Code.html</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>XLN Audio</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.xlnaudio.com/support">http://www.xlnaudio.com/support</a></td>
								</tr>
								<tr>
									<td style="padding:0 0 10px 0;"><b>Zplane</b><br />
									<a style="color:#222222; text-decoration:underline;" href="http://www.zplane.de/products/myaccount/register-products">http://www.zplane.de/products/myaccount/register-products</a></td>
								</tr>
							</table></td>
						</tr>
					</custom>
					<tr>
						<td height="14" style="padding:0 0 0 0; font-size:14px; line-height:1px;">&nbsp;</td>
					</tr>
				</table>
			
			Please note, certain software titles require a <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/Pace-iLok-2-106393259-i1753051.gc?source=[SOURCE_CODE]">Pace iLok</custom> or a <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/Steinberg-License-Key-103223087-i1155075.gc?source=[SOURCE_CODE]">Steinberg eLicenser Key/USB dongle</custom> in order to authorize and store the license for the software purchased. You may be asked to create an account prior to downloading.<br /><br />

			If you have any questions please contact the manufacturer or call us at <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.</td>
		</tr>
	</table>