<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Order Confirmation</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="field" name="ORDER_NUM" /></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
			
			Thanks for shopping with us. We've received your order and will process it as soon as possible. We will send you follow-up emails with shipping and tracking information.<br /><br />
			
				<table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;">
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">For your protection, all orders are subject to billing verification. If we need additional information to verify billing identity, we will contact you by email.</td>
					</tr>
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Your order may arrive in multiple shipments; you will not be charged extra.</td>
					</tr>
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Guitar Center Gift Cards ship USPS with no tracking. Delivery may take up to 7&#8211;10 business days</td>
					</tr>
				</table><br />
						
			If you need further assistance with your order, please call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.</td>
		</tr>
	</table>