<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Backorder Notice</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="field" name="ORDER_NUM" /></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
			
			Thank you again for your recent order. Due to an unusually large response, we are temporarily out of stock of the item(s) you ordered. Additional quantities are on order and we expect them soon. Your order will receive priority upon receipt in the warehouse, and we expect to be able to ship your order within 30 days. We are very sorry for the delay and assure you that we are making every effort to speed your order to you.<br /><br />

			If you can't wait and would like to choose an alternative item, please call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span> or visit our <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/GC---Contact-Us-Landing-g10075t0.gc?source=[SOURCE_CODE]">Online Help Center</custom> where you can view our knowledge base or submit a question. We believe the wait will be worthwhile, but the choice is yours.</td>
		</tr>
	</table>