<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:30px 0 30px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="deviceWidth">
				<table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;">
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Orders sent in multiple shipments are not charged extra.</td>
					</tr>
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Shipping charges for the entire order are billed on the first shipment.</td>
					</tr>
				</table><br />
						
			If you need further assistance with your order, please call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.<br /><br />
			
			Thanks for shopping with us,<br />
			<b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Guitar Center</b></td>
		</tr>
	</table>