<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td width="100%" bgcolor="#dfdfdf" height="1" style="padding:0 0 0 0; font-size:1px; mso-line-height-rule:exactly; line-height:1px;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="100%" style="padding:15px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;" class="deviceWidth"><b>Pricing:</b><br />
			Product prices are subject to change and all deals are subject to stock availability. We are not responsible for printing, typographical or photographic representation errors. Online and Call Center prices may vary from those in Guitar Center retail stores. See full <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://gc.guitarcenter.com/financing/pricing.cfm?source=[SOURCE_CODE]">pricing information</custom>.<br /><br />

			<b>Questions?</b><br />
			Visit our <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/GC---Contact-Us-Landing-g10075t0.gc?source=[SOURCE_CODE]">Online Help Center</custom> to email questions and view our knowledge base. Or call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span> for friendly, informed customer service.<br /><br />
			
			<b>Feedback</b>?<br />
			<custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/openears/?source=[SOURCE_CODE]">Tell us</custom> about your customer experience.<br /><br />

			&#169; <custom type="field" name="CURRENT_YEAR" /> Guitar Center, Inc., <span class="mobileLink">PO Box 5111, Thousand Oaks, CA 91359-5111, USA.</span> <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://gc.guitarcenter.com/legal/privacy.cfm?source=[SOURCE_CODE]">Privacy Policy</custom></td>
		</tr>
	</table>