<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Password Reset Confirmation</td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 0 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="FIRST_NAME" />,</b><br /><br />
			
			Your password was successfully changed. If you did not make this change or are having trouble accessing your account, please contact us immediately at <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.<br /><br />
			
			<custom type="anchor" style="text-decoration:underline; color:#222222;" href="https://www.guitarcenter.com/myaccount/?source=[SOURCE_CODE]">Log into your account</custom>.</td>
		</tr>
	</table>