<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Shipping Confirmation</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="field" name="ORDER_NUM" /></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
			
			Thanks for shopping with us. Your order has been shipped and is on its way. Changes can no longer be made to this order, but if you need to return an item from this shipment or want to manage other orders, please visit <custom type="anchor" style="color:#222222; text-decoration:underline;" href="https://www.guitarcenter.com/myaccount/?source=[SOURCE_CODE]">My Account</custom> on <custom type="anchor" style="color:#222222; text-decoration:none;" href="http://www.guitarcenter.com/?source=[SOURCE_CODE]">GuitarCenter.com</custom>.<br /><br />

				<table width="100%" border="0" cellpadding="0" cellspacing="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;">
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Your order may arrive in multiple shipments; you will not be charged extra.</td>
					</tr>
					<tr>
						<td valign="top" style="padding:0 5px 0 0; font-weight:bold; font-size:14px; mso-line-height-rule:exactly; line-height:18px;">&#8226;</td>
						<td valign="top" style="padding:0 0 0 0;">Packages shipped during weekend hours (Friday afternoon through Sunday evening) will not arrive to the UPS sort facilities until Monday.</td>
					</tr>
				</table></td>
		</tr></td>
		</tr>
	</table>