<custom type="file" name="order-cancellation-copy-1" />
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="border-bottom:1px solid #dfdfdf;" class="deviceWidth">
		<tr>
			<td width="580" valign="bottom" style="padding:30px 0 4px 0; font-family:arial,helvetica,sans-serif; font-size:16px; font-weight:bold; color:#222222; mso-line-height-rule:exactly; line-height:20px; -webkit-text-size-adjust:100%;">Cancelled Item(s)</td>
		</tr>
	</table>
	<custom type="file" name="product-detail" repeatable="yes" />
	<custom type="file" name="order-cancellation-copy-2" />