<tr>
							<td width="7" valign="top" style="padding:2px 4px 0 0; font-weight:bold; font-size:13px; mso-line-height-rule:exactly; line-height:17px;">&#8226;</td>
							<td width="573" valign="top" style="padding:2px 0 0 0;"><custom type="field" name="KIT_ITEM_NAME" />  <custom type="field" name="KIT_QUANTITY" optional="yes" minvalue="2">&nbsp;(<custom type="field" name="KIT_QUANTITY" format="number" />)</custom></td>
						</tr>