<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Product Alert</td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 5px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="FIRST_NAME" />,</b><br /><br />
			
			The item you're interested in can be ordered online. Please be advised many shipments are pre-sold even before they arrive in our warehouse. We recommend you order this item now to guarantee your place in line. Your credit card will not be charged until the item ships.</td>
		</tr>
	</table>