<style type="text/css">
		/* Various email client hacks */
		.ExternalClass * {line-height:100% !important;}
		.ReadMsgBody{width:100%; background-color:#ffffff; margin:0 auto 0 auto;}
		.ExternalClass{width:100%; background-color:#ffffff; margin:0 auto 0 auto;}
		body{width:100%; background-color:#ffffff; margin:0 auto 0 auto; -webkit-font-smoothing:antialiased;}
		table{border-collapse:collapse;}	
		/* Media query for tablets */
		@media only screen and (max-width:640px) { body#yahoo .deviceWidth{width:440px !important;} body#yahoo .center{text-align:center !important;} body#yahoo .logoPad{padding:10px 170px 6px 170px !important;} body#yahoo .logo{width:100px !important;} body#yahoo .phonePad1{padding:8px 15px 0 15px !important;} body#yahoo .phonePad2{padding:2px 15px 0 15px !important;} body#yahoo .topLinks{padding:10px 15px 12px 15px !important; border-top:none !important; border-bottom:1px solid #dedede !important;} body#yahoo .widthAuto{width:auto !important;} body#yahoo .socialShare{padding:0 16px 0 0 !important;} body#yahoo .topPadZero{padding-top:0 !important;} body#yahoo .footLinks{padding:6px 65px 6px 65px !important; line-height:24px !important;} }	
		/* Media query for phones */
		@media only screen and (max-width:479px) { body#yahoo .deviceWidth{width:280px !important;} body#yahoo .center{text-align:center !important;} body#yahoo .logoPad{padding:10px 90px 6px 90px !important;} body#yahoo .logo{width:80px !important;} body#yahoo .phonePad1{padding:7px 5px 0 5px !important; font-size:15px !important;} body#yahoo .phonePad2{padding:2px 5px 0 5px !important; font-size:15px !important;} body#yahoo .topLinks{padding:9px 5px 12px 5px !important; border-top:none !important; border-bottom:1px solid #dedede !important; font-size:12px !important; mso-line-height-rule:exactly !important; line-height:16px !important;} body#yahoo .topPadZero{padding-top:0 !important;} body#yahoo .widthAuto{width:auto !important;} body#yahoo .socialShare{padding:0 17px 0 0 !important;} body#yahoo .socialImg{padding:0 0 0 0 !important; width:21px !important;} body#yahoo .footLinks{padding:6px 40px 6px 40px !important; line-height:24px !important;} }
		/* Attempt to make phone numbers/addresses/dates the style we want */
		.mobileLink *{text-decoration:none !important; color:#222222 !important;}
	</style>