<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:0 0 30px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;">If you need further assistance with your return, please call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.<br /><br />
			
			Thanks for shopping with us,<br />
			<b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Guitar Center</b>
		</tr>
	</table>