<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
      <tr>
         <td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Return Authorization</td>
      </tr>
      <tr>
         <td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">RA #: <custom type="field" name="RA_NUM" /></td>
      </tr>
   </table>
   <table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
      <tr>
         <td style="padding:20px 0 20px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
         
         Please follow the instructions below to return your merchandise. Our full return policy is <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://gc.guitarcenter.com/financing/30_30.cfm?source=[SOURCE_CODE]&esid=Return%20Policy">listed here</custom>.<br /><br />

         <b>1) Write your RA # (shown above) on the return shipping label:</b><br />
         The label is located on the back of your invoice.
         <custom type="field" name="RETURN_LABEL_URL" optional="yes">
            If you need to print a new return shipping label, use the link(s) below.<br />
               <table border="0" cellpadding="0" cellspacing="0" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%; margin-bottom:0px;">
                  <custom type="file" name="order-return-label" repeatable="yes" />
                  <tr>
                     <td colspan="2" height="13" style="font-size:13px; line-height:1px;">&nbsp;</td>
                  </tr>
               </table>
         </custom>
         <br /><br />
         
         <b>2) Use the original packaging to return your item(s):</b><br />
         Place the invoice inside the package with your items. Include all materials such as warranty cards, owner's manuals, etc. Pack carefully to avoid potential damage during shipment. We recommend that you insure your return shipment, since you are responsible for the items until our warehouse receives them. (If you were sent a prepaid label the package is already insured.)<br /><br />

         <b>3) Return to:</b><br />
            <table border="0" cellpadding="0" cellspacing="0">
               <tr>
                  <td style="padding:5px 5px 5px 25px; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;">Guitar Center, Inc.<br />
                  RA # <custom type="field" name="RA_NUM" /><br />
                  4005 N. Norfleet<br />
                  Kansas City, MO 64161-9231</td>
               </tr>
               <tr>
                  <td colspan="2" height="13" style="font-size:13px; line-height:1px;">&nbsp;</td>
               </tr>
            </table>
            
         <b>4) Return the items in the same condition as received:</b><br />
         Make sure your items are free from signs of wear or abuse or they will be assessed a restocking fee. If the items come back in new condition, you can expect a full refund unless you received free shipping on your purchase. The value of the uncharged shipping cost will be deducted from your refund.<br /><br />

         <b>5) Timelines:</b><br />
         Once your item is received it will take 1-2 days for us to resolve your return. Please allow an additional 5-7 business days to receive your credit or exchange item.</td>
      </tr>
   </table>