<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Return Confirmation</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="anchor" style="color:#222222; text-decoration:underline;" href="https://www.guitarcenter.com/myaccount/order.aspx?source=[SOURCE_CODE]&on=[ORDER_NUM]"><custom type="field" name="ORDER_NUM" /></custom></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 0 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello Deb,</b><br /><br />
			
			Thank you for shopping at Guitar Center. The items below have been received by our returns center. Your primary payment method will be credited/debited in accordance with our <custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://gc.guitarcenter.com/financing/30_30.cfm?source=[SOURCE_CODE]&esid=Return%20Policy">return policy</custom>.</td>
		</tr>
	</table>