<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="100%" colspan="2" height="8" style="font-size:8px; line-height:1px;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="100%" colspan="2" style="padding:0 0 0 0; border-bottom:4px double #dfdfdf;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="465" align="right" style="padding:10px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;">Total:</td>
			<td width="115" align="right" style="padding:10px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;">$<custom type="field" name="TOTAL" format="currency" /></td>
		</tr>		
		<tr>
			<td align="center" width="100%" colspan="2" style="padding:15px 15px 0 15px;" class="deviceWidth">
				<table border="0" cellpadding="0" cellspacing="0" width="140" bgcolor="#ac0900" style="-webkit-border-radius:4px 4px 4px 4px; -moz-border-radius:4px 4px 4px 4px; border-radius:4px 4px 4px 4px; font-family:arial,helvetica,sans-serif; font-size:13px; font-weight:bold; color:#ffffff; text-decoration:none;">
					<tr>
						<!-- Keep the line break before the anchor tag or the SMTP server may insert a ! in the HTML due to code line exceeding 1,000 char. -->
						<td width="140" align="center" style="padding:10px 0 10px 0; vertical-align:middle; display:inline-block; zoom:1; *display:inline; vertical-align:baseline; margin:0 0 0 0; outline:none; background:-webkit-gradient(linear, left top, left bottom, from(#cc0000), to(#9b0101)); background:-webkit-linear-gradient(top, #cc0000, #9b0101); background:-moz-linear-gradient(top, #cc0000, #9b0101); background:-ms-linear-gradient(top, #cc0000, #9b0101); background:-o-linear-gradient(top, #cc0000, #9b0101); filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#cc0000', endColorstr='#9b0101'); -webkit-border-radius:4px 4px 4px 4px; -moz-border-radius:4px 4px 4px 4px; border-radius:4px 4px 4px 4px; -webkit-box-shadow:rgba(100,0,0,1) 0 1px 0; -moz-box-shadow:rgba(100,0,0,1) 0 1px 0; box-shadow:rgba(100,0,0,1) 0 1px 0; text-shadow:rgba(0,0,0,.4) 0 1px 0;">
						<custom type="anchor" style="color:#ffffff; text-decoration:none; display:block;" href="[CART_URL]?source=[SOURCE_CODE]"><span style="color:#ffffff;">Add To Cart</span></custom></td>
					</tr>
				</table></td>
		</tr>
	</table>