<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Custom Quote</td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 0 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="FIRST_NAME" />,</b><br /><br />
			
			To take advantage of these custom prices, just click the &quot;Add To Cart&quot; button below. You may add or remove items from your cart at that time. Please act soon&#8212;custom pricing in this quote will automatically expire in 10 days (<custom type="field" name="QUOTE_EXPIRATION" />).<br /><br />
			
			Custom quotes may not be combined with any other offer. Due to manufacturer restrictions, a U.S. shipping address may be required.<br /><br />
			
			If you need further assistance, please call <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.</td>
		</tr>
	</table>