<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">My Wish List</td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 0 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="FIRST_NAME" />,</b><br /><br />
			
			<custom type="field" name="WISHLIST_FNAME" /> sent you a copy of his/her Guitar Center Wish List and included this message for you:<br /><br />
			
				<table border="0" cellpadding="0" cellspacing="0" width="90%">
					<tr>
						<td style="padding:0 30px 0 30px; font-family:arial,helvetica,sans-serif; font-size:13px; color:#cc0000; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><custom type="field" name="WISHLIST_MESSAGE" /></td>
					</tr>
				</table></td>
		</tr>
	</table>