<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:30px 0 30px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="deviceWidth"><custom type="field" name="WISHLIST_FNAME" /> chooses Guitar Center, and we hope you will too. If you should have any questions or concerns, or you're not 100% satisfied, please feel free to call the number below or contact your preferred Guitar Center store location.<br /><br />

			We look forward to helping you with this Wish List and anything else you may need in the future.<br /><br />
			
			Sincerely,<br />
			<b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Guitar Center</b><br />
			<custom type="anchor" style="color:#222222; text-decoration:underline;" href="http://www.guitarcenter.com/?source=[SOURCE_CODE]">http://www.guitarcenter.com</custom><br />
			<span style="font-weight:bold;" class="mobileLink">866-498-7882</span></td>
		</tr>
	</table>