<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="deviceWidth">
		<tr>
			<td align="center" style="padding:5px 0 10px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth"><custom type="field" name="WISHLIST_FNAME" /> <custom type="field" name="WISHLIST_LNAME" /> wants to share this with you.</td>
		</tr>
	</table>