<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td width="100%" bgcolor="#dfdfdf" height="1" style="padding:0 0 0 0; font-size:1px; mso-line-height-rule:exactly; line-height:1px;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="100%" style="padding:15px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;" class="deviceWidth">&#169; <custom type="field" name="CURRENT_YEAR" /> Guitar Center, Inc., <span class="mobileLink">PO Box 5111, Thousand Oaks, CA 91359-5111, USA.</span></td>
		</tr>
	</table>