<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Backorder Notice</td>
		</tr>
		<tr>
			<td width="580" align="right" style="padding:2px 0 0 0; font-size:12px; mso-line-height-rule:exactly; line-height:16px;" class="deviceWidth">Order #: <custom type="anchor" style="color:#222222; text-decoration:underline;" href="https://www.guitarcenter.com/myaccount/order.aspx?source=[SOURCE_CODE]&on=[ORDER_NUM]"><custom type="field" name="ORDER_NUM" /></custom></td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
			
			We are sorry but the items shown below remain out of stock. Additional merchandise is on order with our vendor and we expect to ship within 30 days.<br /><br />
			
			<b>Unless we hear from you within 14 days, we'll assume you cannot wait and your order will be cancelled.</b> Federal regulations will not allow us to hold your order any longer without your express written consent. If you can wait, please call us at <span style="font-weight:bold;" class="mobileLink">866-498-7882</span>.</td>
		</tr>
	</table>