<custom type="field" name="NotificationType" optional="yes" mustEqual="FRAUD_NOTE">
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="deviceWidth">
		<tr>
			<td align="center" style="padding:5px 0 10px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">Please give us a call at <span class="mobileLink">866-498-7883</span>.</td>
		</tr>
	</table>
</custom>
<custom type="field" name="NotificationType" optional="yes" mustEqual="CC_DECLINED">
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" class="deviceWidth">
		<tr>
			<td align="center" style="padding:5px 0 10px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">We need some additional information.</td>
		</tr>
	</table>
</custom>