<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="border-bottom:1px solid #dfdfdf;" class="deviceWidth">
		<tr>
			<td width="100" valign="bottom" style="padding:30px 0 4px 0; font-family:arial,helvetica,sans-serif; font-size:16px; font-weight:bold; color:#222222; mso-line-height-rule:exactly; line-height:20px; -webkit-text-size-adjust:100%;">Package <custom type="field" name="PKG_NUM" /></td>
			<td width="480" valign="bottom" align="right" style="padding:30px 0 6px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="widthAuto">Tracking: <custom type="anchor" style="color:#222222; text-decoration:underline;" href="[TRACKING_URL]"><custom type="field" name="TRACKING_NUM" /></custom></td>
		</tr>
	</table>
	<custom type="file" name="product-detail" repeatable="yes" />