<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 30px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="deviceWidth">Thanks,<br />
			<b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;"><custom type="field" name="BILLING_FNAME" /> <custom type="field" name="BILLING_LNAME" /></b><br />
			<custom type="anchor" style="text-decoration:underline; color:#222222;" href="mailto:[BILLING_EMAIL]">[BILLING_EMAIL]</custom></td>
		</tr>
	</table>