<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" style="font-family:arial,helvetica,sans-serif; color:#222222; -webkit-text-size-adjust:100%;" class="deviceWidth">
		<tr>
			<td width="580" align="right" style="padding:12px 0 0 0; font-size:16px; font-weight:bold; mso-line-height-rule:exactly; line-height:20px;" class="deviceWidth">Write A Review</td>
		</tr>
	</table>
	<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td style="padding:20px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;"><b style="font-size:16px; mso-line-height-rule:exactly; line-height:20px;">Hello <custom type="field" name="BILLING_FNAME" />,</b><br /><br />
			
			It's been a couple weeks since we shipped your gear, and we're hoping you'll let your fellow customers know what you think. If you'd like to review a product from your order, click the &quot;Review Now&quot; link below.</td>
		</tr>
	</table>