<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
		<tr>
			<td width="100%" bgcolor="#dfdfdf" height="1" style="padding:0 0 0 0; font-size:1px; mso-line-height-rule:exactly; line-height:1px;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="100%" align="center" style="padding:12px 0 12px 0; font-family:arial,helvetica,sans-serif; font-size:13px; color:#222222; mso-line-height-rule:exactly; line-height:17px; -webkit-text-size-adjust:100%;" class="footLinks deviceWidth"><custom type="anchor" style="color:#222222; text-decoration:none;" href="http://www.guitarcenter.com/GCStudios-g26427t0.gc?source=[SOURCE_CODE]">GC Studios</custom>
			&nbsp;&nbsp;&#124;&nbsp;&nbsp; <custom type="anchor" style="color:#222222; text-decoration:none;" href="http://stores.guitarcenter.com/gc-garage?source=[SOURCE_CODE]">GC Garage</custom>
			&nbsp;&nbsp;&#124;&nbsp;&nbsp; <custom type="anchor" style="color:#222222; text-decoration:none;" href="http://www.guitarcenter.com/Rental-Locations-g26678t0.gc?source=[SOURCE_CODE]">GC Rentals</custom>
			&nbsp;&nbsp;&#124;&nbsp;&nbsp; <custom type="anchor" style="color:#222222; text-decoration:none;" href="http://musicmentor.guitarcenter.com/?source=[SOURCE_CODE]">Music Mentor</custom>
			&nbsp;&nbsp;&#124;&nbsp;&nbsp; <a style="color:#222222; text-decoration:none;" href="https://twitter.com/GCSoundAdvice">Sound Advice</a>
			&nbsp;&nbsp;&#124;&nbsp;&nbsp; <a style="color:#222222; text-decoration:none;" href="http://guitarcenter.tumblr.com/">Events</a></td>
		</tr>
		<tr>
			<td width="100%" bgcolor="#dfdfdf" height="1" style="padding:0 0 0 0; font-size:1px; mso-line-height-rule:exactly; line-height:1px;" class="deviceWidth">&nbsp;</td>
		</tr>
		<tr>
			<td width="100%" style="padding:15px 0 15px 0; font-family:arial,helvetica,sans-serif; font-size:12px; color:#222222; mso-line-height-rule:exactly; line-height:16px; -webkit-text-size-adjust:100%;" class="deviceWidth">&#169; <custom type="field" name="CURRENT_YEAR" /> Guitar Center, Inc., <span class="mobileLink">PO Box 5111, Thousand Oaks, CA 91359-5111, USA.</span></td>
		</tr>
	</table>